### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by fb82** [ZJULearning/efanna#4]
Hi,
I found your code very interesting and I would like to use for my research (SIFT-like descriptors testing), but I have two questions:
1. Does EFANNA support  L1 (i.e. Manhattan) distance?
2. If descriptor elements are integer in the range 0-15 (i.e. nibbles), does the code need a specific tuning of some parameters  (such as those related to the hash function)?

Thanks in advance

**Comment by CongFu92** [comment]
1. EFANNA can support L1 distance, but I haven't implement it yet. And sorry, recently I have no time for that. If you have to use L1, you may implement a new distance class in the distance.hpp similar to the L2Distance class. It should be simple.
2. The code doesn't need specific tuning according to data type. If the precision of the graph or search is low, you may just try bigger parameters.
Thank you for your attention!

**Comment by ashfaq92** [comment]
Hi,
Thank you for sharing the code. My questions are: 
1. Does your method support data point updates after creating the index?
2. Is data point size have to be given in advance for the initializing index?

The reason of these questions is: HNSW has to be given size of index in advance. But once size is given (let suppose 1000 points) we can add points into it incrementally
